Add functionality to follow and stalk buttons
skornel02/szte-IB152l-2023-2 pull request #6
Opened 2024-04-13 18:14 UTC by hgergely03

2024-04-13 18:58 UTC, skornel02 requested changes

2024-04-13 18:58 UTC, skornel02 commented on Backend/Pages/Profile.cshtml
>                  </button>
Please make this actually be an anchor pretty please 
![pretty](https://gifdb.com/images/high/pretty-please-cute-agnes-266iavileow1fbtp.gif)

2024-04-14 07:30 UTC, hgergely03 commented on Backend/Pages/Profile.cshtml
>                  </button>
Everyone's entitled to their opinions ¯\_(ツ)_/¯

2024-04-14 09:38 UTC, skornel02 approved these changes
LGTM!

2024-04-14 09:38 UTC, merged